name: "Build Tiny NVR Docker Image"

on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'     
        required: false
        default: false
  push:
    branches:
      - main

jobs:
  build-tiny-nvr-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}

      - uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: tiny-nvr
          dockerfile: Dockerfile
          addLatest: true
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT_TOKEN }}
